### ISSUE TITLE
Use HtmlRenderer instead of RazorViewComponentStringRenderer

### ISSUE THREAD

**Issue by krebil** [krebil/Hotwired-dot-net#3]
HtmlRenderer was added in .NET 8. 

This should be replace RazorViewComponentStringRenderer

**Comment by apfohl** [comment]
I wonder how you can achieve this? I tried to implement it, but mainly the HtmlRenderer is available for rendering RazorComponents (Blazor). I mean I‘m not sure if it‘s not possible, but it doesn’t look easy.

**Comment by krebil** [comment]
@apfohl 

You are right. I wrote this issue before I did any research just as a reminder to myself. 

I do still want to consider if there is any merit to supporting both types of components. But using blazor at all probably defeats the purpose of a Hyper media driven application

**Comment by apfohl** [comment]
> @apfohl 
> 
> 
> 
> You are right. I wrote this issue before I did any research just as a reminder to myself. 
> 
> 
> 
> I do still want to consider if there is any merit to supporting both types of components. But using blazor at all probably defeats the purpose of a Hyper media driven application

I agree, the concept of using Turbo is different to Blazer and serves a different purpose.

I would love to have a Stack using backend rendering and Turbo for Frontend updating.

I took my own Spin on it but lacking the ability to composing ViewComponents wich just C# in my controllers: https://github.com/apfohl/HotwiredBooks 

A nice solution for this would be nice. That's why I tried the HtmlRenderer approach.

I also implemented the setting of the return type for TurboStreams as a Controller attribute and use only TagHelpers for composing TurboFrame and TurboStream responses.

**Comment by krebil** [comment]
Attributes are a good take on how to handle response types for controllers you control. I've used the current pattern to overwrite controller behaviour from CMS eg. Form submissions in these cases you may not be able to add attributes. But maybe having both options is optimal.

I'm not a huge fan of the current rendering mechanism either, I'd like to have a neater way of doing it. However I find that I'm not using it all that much if I try to structure my application to mostly use streams for very specific out of bounds swaps for frame requests then I can get away with including partial views depending on what data gets passed to my view components.

Of course i would still need the rendering service if the app uses Web sockets which kinda sucks.

**Comment by apfohl** [comment]
I get you. This is kinda tricky to do. Will also try out some things for streaming. But nothing concrete at the moment.

Keep up the good work, it's inspiring. 👍

**Comment by krebil** [comment]
Thanks man, swing by you wanna talk always fun to talk shop

**Comment by krebil** [comment]
@apfohl If you feel up for it, I would love a PR for the attributes 😄
